# Generated by Django 6.0.3 on 2026-04-15 23:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedido', '0001_initial'),
        ('produto', '0003_alter_produto_preco'),
        ('produtor', '0001_initial'),
        ('varejista', '0002_rename_user_varejista_id_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id_avaliacao', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.pedido')),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto')),
                ('id_produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtor.produtor')),
                ('id_varejista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='varejista.varejista')),
            ],
        ),
    ]
