# Generated by Django 6.0.3 on 2026-04-23 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0001_initial'),
        ('pedido', '0002_alter_pedido_id_pedido_rename_id_pedido_pedido_id_and_more'),
        ('produto', '0004_alter_produto_id_produto_and_more'),
        ('produtor', '0001_initial'),
        ('varejista', '0003_rename_id_usuario_varejista_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='id_avaliacao',
            field=models.AutoField(db_column='id_avaliacao', primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='avaliacao',
            old_name='id_avaliacao',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='id_pedido',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='id_produto',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='id_produtor',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='id_varejista',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='pedido',
            field=models.ForeignKey(db_column='id_pedido', default=1, on_delete=django.db.models.deletion.CASCADE, to='pedido.pedido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='produto',
            field=models.ForeignKey(db_column='id_produto', default=1, on_delete=django.db.models.deletion.CASCADE, to='produto.produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='produtor',
            field=models.ForeignKey(db_column='id_produtor', default=1, on_delete=django.db.models.deletion.CASCADE, to='produtor.produtor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='varejista',
            field=models.ForeignKey(db_column='id_varejista', default=1, on_delete=django.db.models.deletion.CASCADE, to='varejista.varejista'),
            preserve_default=False,
        ),
    ]
