# Generated by Django 6.0.3 on 2026-04-23 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0002_alter_avaliacao_id_avaliacao_and_more'),
        ('varejista', '0003_rename_id_usuario_varejista_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='varejista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='varejista.varejista'),
        ),
    ]
