# Generated by Django 6.0.3 on 2026-04-15 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('varejista', '0002_rename_user_varejista_id_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('ENTREGUE', 'Entregue')], default='PENDENTE', max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('id_varejista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='varejista.varejista')),
            ],
        ),
    ]
