# Generated by Django 6.0.3 on 2026-04-23 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
        ('varejista', '0003_rename_id_usuario_varejista_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='id_pedido',
            field=models.AutoField(db_column='id_pedido', primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='id_pedido',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='id_varejista',
        ),
        migrations.AddField(
            model_name='pedido',
            name='varejista',
            field=models.ForeignKey(db_column='id_varejista', default=1, on_delete=django.db.models.deletion.CASCADE, to='varejista.varejista'),
            preserve_default=False,
        ),
    ]
