# Generated by Django 6.0.3 on 2026-04-04 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='produtor', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tipo_documento', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], max_length=4)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('nome_fantasia', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
