# Generated by Django 6.0.3 on 2026-05-07 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItemImage',
            fields=[
                ('id', models.BigAutoField(db_column='id_wishlist_item_image', primary_key=True, serialize=False)),
                ('product_external_key', models.TextField(unique=True)),
                ('image', models.ForeignKey(db_column='id_image', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_item_images', to='image.image')),
            ],
            options={
                'db_table': 'wishlist_item_image',
            },
        ),
    ]
