# Generated by Django 6.0.3 on 2026-05-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist_item_image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitemimage',
            name='product_external_key',
            field=models.TextField(db_column='product_external_key', unique=True),
        ),
    ]
