--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4
-- Dumped by pg_dump version 16.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: tiger; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA tiger;


ALTER SCHEMA tiger OWNER TO postgres;

--
-- Name: tiger_data; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA tiger_data;


ALTER SCHEMA tiger_data OWNER TO postgres;

--
-- Name: topology; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA topology;


ALTER SCHEMA topology OWNER TO postgres;

--
-- Name: SCHEMA topology; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON SCHEMA topology IS 'PostGIS Topology schema';


--
-- Name: fuzzystrmatch; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS fuzzystrmatch WITH SCHEMA public;


--
-- Name: EXTENSION fuzzystrmatch; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION fuzzystrmatch IS 'determine similarities and distance between strings';


--
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;


--
-- Name: EXTENSION postgis; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION postgis IS 'PostGIS geometry and geography spatial types and functions';


--
-- Name: postgis_tiger_geocoder; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder WITH SCHEMA tiger;


--
-- Name: EXTENSION postgis_tiger_geocoder; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION postgis_tiger_geocoder IS 'PostGIS tiger geocoder and reverse geocoder';


--
-- Name: postgis_topology; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis_topology WITH SCHEMA topology;


--
-- Name: EXTENSION postgis_topology; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION postgis_topology IS 'PostGIS topology spatial types and functions';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: address; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.address (
    id_address bigint NOT NULL,
    street character varying(150) NOT NULL,
    number character varying(10) NOT NULL,
    complement text NOT NULL,
    neighborhood character varying(100) NOT NULL,
    city character varying(100) NOT NULL,
    state character varying(2) NOT NULL,
    postal_code character varying(10) NOT NULL,
    id_user bigint NOT NULL,
    latitude numeric(9,6),
    longitude numeric(9,6)
);


ALTER TABLE public.address OWNER TO postgres;

--
-- Name: address_id_address_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.address ALTER COLUMN id_address ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.address_id_address_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.category (
    id_category integer NOT NULL,
    name character varying(100) NOT NULL,
    is_active boolean NOT NULL
);


ALTER TABLE public.category OWNER TO postgres;

--
-- Name: category_id_category_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.category ALTER COLUMN id_category ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_id_category_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: default_product_image; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.default_product_image (
    id_default_product_image bigint NOT NULL,
    product_external_key text NOT NULL,
    product_name character varying(150) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    id_image bigint
);


ALTER TABLE public.default_product_image OWNER TO postgres;

--
-- Name: default_product_image_id_default_product_image_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.default_product_image ALTER COLUMN id_default_product_image ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.default_product_image_id_default_product_image_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: image; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.image (
    id_image bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    blob bytea NOT NULL,
    mime_type character varying(100) NOT NULL
);


ALTER TABLE public.image OWNER TO postgres;

--
-- Name: image_id_image_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.image ALTER COLUMN id_image ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.image_id_image_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."order" (
    id_order bigint NOT NULL,
    status character varying(20) NOT NULL,
    total_value numeric(10,2) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    id_producer bigint NOT NULL,
    id_retailer bigint NOT NULL,
    fee_value numeric(10,2) NOT NULL,
    subtotal_value numeric(10,2) NOT NULL,
    payment_method character varying(20)
);


ALTER TABLE public."order" OWNER TO postgres;

--
-- Name: order_id_order_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."order" ALTER COLUMN id_order ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_id_order_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_item; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.order_item (
    id_order_item bigint NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    id_order bigint NOT NULL,
    id_product bigint NOT NULL,
    CONSTRAINT order_item_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.order_item OWNER TO postgres;

--
-- Name: order_item_id_order_item_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.order_item ALTER COLUMN id_order_item ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_item_id_order_item_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: producer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.producer (
    id_producer bigint NOT NULL,
    document_type character varying(4) NOT NULL,
    document_number character varying(20) NOT NULL,
    trade_name character varying(150) NOT NULL,
    id_user bigint NOT NULL
);


ALTER TABLE public.producer OWNER TO postgres;

--
-- Name: producer_id_producer_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.producer ALTER COLUMN id_producer ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.producer_id_producer_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product (
    id_product bigint NOT NULL,
    name character varying(150) NOT NULL,
    description text,
    total_quantity double precision NOT NULL,
    reserved_quantity double precision NOT NULL,
    price numeric(10,2) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    id_category integer NOT NULL,
    id_producer bigint NOT NULL
);


ALTER TABLE public.product OWNER TO postgres;

--
-- Name: product_id_product_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.product ALTER COLUMN id_product ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_id_product_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_image; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product_image (
    id_product_image bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    id_image bigint NOT NULL,
    id_product bigint NOT NULL
);


ALTER TABLE public.product_image OWNER TO postgres;

--
-- Name: product_image_id_product_image_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.product_image ALTER COLUMN id_product_image ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_image_id_product_image_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: retailer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.retailer (
    id_retailer bigint NOT NULL,
    document_type character varying(4) NOT NULL,
    document_number character varying(20) NOT NULL,
    trade_name character varying(150) NOT NULL,
    id_user bigint NOT NULL
);


ALTER TABLE public.retailer OWNER TO postgres;

--
-- Name: retailer_id_retailer_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.retailer ALTER COLUMN id_retailer ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.retailer_id_retailer_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: review; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.review (
    id_review bigint NOT NULL,
    rating double precision NOT NULL,
    comment text,
    created_at timestamp with time zone NOT NULL,
    id_order bigint NOT NULL,
    id_producer bigint NOT NULL,
    id_product bigint NOT NULL,
    id_retailer bigint NOT NULL
);


ALTER TABLE public.review OWNER TO postgres;

--
-- Name: review_id_review_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.review ALTER COLUMN id_review ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_id_review_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    id_user bigint NOT NULL,
    name character varying(255) NOT NULL,
    email character varying(254) NOT NULL,
    user_type character varying(50) NOT NULL,
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_user_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id_user ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_user_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wishlist; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wishlist (
    id_wishlist bigint NOT NULL,
    id_retailer bigint NOT NULL
);


ALTER TABLE public.wishlist OWNER TO postgres;

--
-- Name: wishlist_id_wishlist_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wishlist ALTER COLUMN id_wishlist ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wishlist_id_wishlist_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wishlist_item; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wishlist_item (
    id_wishlist_item bigint NOT NULL,
    product_external_key text NOT NULL,
    product_name character varying(150) NOT NULL,
    id_wishlist bigint NOT NULL
);


ALTER TABLE public.wishlist_item OWNER TO postgres;

--
-- Name: wishlist_item_id_wishlist_item_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wishlist_item ALTER COLUMN id_wishlist_item ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wishlist_item_id_wishlist_item_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: address address_id_user_c498b415_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.address
    ADD CONSTRAINT address_id_user_c498b415_uniq UNIQUE (id_user);


--
-- Name: address address_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.address
    ADD CONSTRAINT address_pkey PRIMARY KEY (id_address);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: category category_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_name_key UNIQUE (name);


--
-- Name: category category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (id_category);


--
-- Name: default_product_image default_product_image_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.default_product_image
    ADD CONSTRAINT default_product_image_pkey PRIMARY KEY (id_default_product_image);


--
-- Name: default_product_image default_product_image_product_external_key_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.default_product_image
    ADD CONSTRAINT default_product_image_product_external_key_key UNIQUE (product_external_key);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: image image_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.image
    ADD CONSTRAINT image_pkey PRIMARY KEY (id_image);


--
-- Name: order_item order_item_id_order_id_product_e1ab01a5_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_item
    ADD CONSTRAINT order_item_id_order_id_product_e1ab01a5_uniq UNIQUE (id_order, id_product);


--
-- Name: order_item order_item_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_item
    ADD CONSTRAINT order_item_pkey PRIMARY KEY (id_order_item);


--
-- Name: order order_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT order_pkey PRIMARY KEY (id_order);


--
-- Name: producer producer_document_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producer
    ADD CONSTRAINT producer_document_number_key UNIQUE (document_number);


--
-- Name: producer producer_id_user_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producer
    ADD CONSTRAINT producer_id_user_key UNIQUE (id_user);


--
-- Name: producer producer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producer
    ADD CONSTRAINT producer_pkey PRIMARY KEY (id_producer);


--
-- Name: product_image product_image_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_image
    ADD CONSTRAINT product_image_pkey PRIMARY KEY (id_product_image);


--
-- Name: product product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pkey PRIMARY KEY (id_product);


--
-- Name: retailer retailer_document_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.retailer
    ADD CONSTRAINT retailer_document_number_key UNIQUE (document_number);


--
-- Name: retailer retailer_id_user_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.retailer
    ADD CONSTRAINT retailer_id_user_key UNIQUE (id_user);


--
-- Name: retailer retailer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.retailer
    ADD CONSTRAINT retailer_pkey PRIMARY KEY (id_retailer);


--
-- Name: review review_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_pkey PRIMARY KEY (id_review);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id_user);


--
-- Name: wishlist wishlist_id_retailer_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wishlist
    ADD CONSTRAINT wishlist_id_retailer_key UNIQUE (id_retailer);


--
-- Name: wishlist_item wishlist_item_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wishlist_item
    ADD CONSTRAINT wishlist_item_pkey PRIMARY KEY (id_wishlist_item);


--
-- Name: wishlist wishlist_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wishlist
    ADD CONSTRAINT wishlist_pkey PRIMARY KEY (id_wishlist);


--
-- Name: address_latitude_86329165; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX address_latitude_86329165 ON public.address USING btree (latitude);


--
-- Name: address_longitude_fe8b23b5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX address_longitude_fe8b23b5 ON public.address USING btree (longitude);


--
-- Name: address_postgis_point_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX address_postgis_point_idx ON public.address USING gist (((public.st_setsrid(public.st_makepoint((longitude)::double precision, (latitude)::double precision), 4326))::public.geography)) WHERE ((latitude IS NOT NULL) AND (longitude IS NOT NULL));


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: category_name_15cb1e98_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX category_name_15cb1e98_like ON public.category USING btree (name varchar_pattern_ops);


--
-- Name: default_pro_product_899833_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX default_pro_product_899833_idx ON public.default_product_image USING btree (product_external_key);


--
-- Name: default_product_image_id_image_ada5024d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX default_product_image_id_image_ada5024d ON public.default_product_image USING btree (id_image);


--
-- Name: default_product_image_product_external_key_e052de33_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX default_product_image_product_external_key_e052de33_like ON public.default_product_image USING btree (product_external_key text_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: order_id_producer_bc372242; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX order_id_producer_bc372242 ON public."order" USING btree (id_producer);


--
-- Name: order_id_retailer_fa2c9aa0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX order_id_retailer_fa2c9aa0 ON public."order" USING btree (id_retailer);


--
-- Name: order_item_id_order_f3306a7f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX order_item_id_order_f3306a7f ON public.order_item USING btree (id_order);


--
-- Name: order_item_id_product_2ad5373f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX order_item_id_product_2ad5373f ON public.order_item USING btree (id_product);


--
-- Name: producer_document_number_58b19b67_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX producer_document_number_58b19b67_like ON public.producer USING btree (document_number varchar_pattern_ops);


--
-- Name: product_id_category_b4bdcb78; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX product_id_category_b4bdcb78 ON public.product USING btree (id_category);


--
-- Name: product_id_producer_6129d69c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX product_id_producer_6129d69c ON public.product USING btree (id_producer);


--
-- Name: product_image_id_image_a45e4544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX product_image_id_image_a45e4544 ON public.product_image USING btree (id_image);


--
-- Name: product_image_id_product_e64928a4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX product_image_id_product_e64928a4 ON public.product_image USING btree (id_product);


--
-- Name: product_is_acti_184a97_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX product_is_acti_184a97_idx ON public.product USING btree (is_active, created_at);


--
-- Name: product_is_acti_dbd057_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX product_is_acti_dbd057_idx ON public.product USING btree (is_active, price);


--
-- Name: product_name_c4c985_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX product_name_c4c985_idx ON public.product USING btree (name);


--
-- Name: product_search_vector_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX product_search_vector_idx ON public.product USING gin (to_tsvector('portuguese'::regconfig, (((COALESCE(name, ''::character varying))::text || ' '::text) || COALESCE(description, ''::text))));


--
-- Name: retailer_document_number_a2b95662_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX retailer_document_number_a2b95662_like ON public.retailer USING btree (document_number varchar_pattern_ops);


--
-- Name: review_id_order_f115de77; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX review_id_order_f115de77 ON public.review USING btree (id_order);


--
-- Name: review_id_producer_13bb28c7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX review_id_producer_13bb28c7 ON public.review USING btree (id_producer);


--
-- Name: review_id_product_8e927e77; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX review_id_product_8e927e77 ON public.review USING btree (id_product);


--
-- Name: review_id_retailer_077f83b2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX review_id_retailer_077f83b2 ON public.review USING btree (id_retailer);


--
-- Name: unique_pending_order_per_retailer_producer; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX unique_pending_order_per_retailer_producer ON public."order" USING btree (id_retailer, id_producer) WHERE ((status)::text = 'PENDING'::text);


--
-- Name: users_email_0ea73cca_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_email_0ea73cca_like ON public.users USING btree (email varchar_pattern_ops);


--
-- Name: wishlist_item_id_wishlist_0b7b09ed; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX wishlist_item_id_wishlist_0b7b09ed ON public.wishlist_item USING btree (id_wishlist);


--
-- Name: address address_id_user_c498b415_fk_users_id_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.address
    ADD CONSTRAINT address_id_user_c498b415_fk_users_id_user FOREIGN KEY (id_user) REFERENCES public.users(id_user) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: default_product_image default_product_image_id_image_ada5024d_fk_image_id_image; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.default_product_image
    ADD CONSTRAINT default_product_image_id_image_ada5024d_fk_image_id_image FOREIGN KEY (id_image) REFERENCES public.image(id_image) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_id_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_id_user FOREIGN KEY (user_id) REFERENCES public.users(id_user) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: order order_id_producer_bc372242_fk_producer_id_producer; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT order_id_producer_bc372242_fk_producer_id_producer FOREIGN KEY (id_producer) REFERENCES public.producer(id_producer) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: order order_id_retailer_fa2c9aa0_fk_retailer_id_retailer; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT order_id_retailer_fa2c9aa0_fk_retailer_id_retailer FOREIGN KEY (id_retailer) REFERENCES public.retailer(id_retailer) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: order_item order_item_id_order_f3306a7f_fk_order_id_order; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_item
    ADD CONSTRAINT order_item_id_order_f3306a7f_fk_order_id_order FOREIGN KEY (id_order) REFERENCES public."order"(id_order) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: order_item order_item_id_product_2ad5373f_fk_product_id_product; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_item
    ADD CONSTRAINT order_item_id_product_2ad5373f_fk_product_id_product FOREIGN KEY (id_product) REFERENCES public.product(id_product) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: producer producer_id_user_e04d8773_fk_users_id_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producer
    ADD CONSTRAINT producer_id_user_e04d8773_fk_users_id_user FOREIGN KEY (id_user) REFERENCES public.users(id_user) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: product product_id_category_b4bdcb78_fk_category_id_category; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_id_category_b4bdcb78_fk_category_id_category FOREIGN KEY (id_category) REFERENCES public.category(id_category) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: product product_id_producer_6129d69c_fk_producer_id_producer; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_id_producer_6129d69c_fk_producer_id_producer FOREIGN KEY (id_producer) REFERENCES public.producer(id_producer) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: product_image product_image_id_image_a45e4544_fk_image_id_image; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_image
    ADD CONSTRAINT product_image_id_image_a45e4544_fk_image_id_image FOREIGN KEY (id_image) REFERENCES public.image(id_image) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: product_image product_image_id_product_e64928a4_fk_product_id_product; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_image
    ADD CONSTRAINT product_image_id_product_e64928a4_fk_product_id_product FOREIGN KEY (id_product) REFERENCES public.product(id_product) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: retailer retailer_id_user_b33776a3_fk_users_id_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--PostgreSQL
1. Install
pg_dump
.
2. In your terminal run the following command On Linux you might need to add sudo before it
$ pg_dump -h <host> -p <port> -d <database_name> -U <username> -s -F p -E UTF-8 -f <output_path>
Example
$ pg_dump -h localhost -p 5432 -d ecommerce -U postgres -s -F p -E UTF-8 -f C:\pg_schema.sql
Copy the dumped SQL content and paste it into this m

ALTER TABLE ONLY public.retailer
    ADD CONSTRAINT retailer_id_user_b33776a3_fk_users_id_user FOREIGN KEY (id_user) REFERENCES public.users(id_user) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: review review_id_order_f115de77_fk_order_id_order; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_id_order_f115de77_fk_order_id_order FOREIGN KEY (id_order) REFERENCES public."order"(id_order) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: review review_id_producer_13bb28c7_fk_producer_id_producer; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_id_producer_13bb28c7_fk_producer_id_producer FOREIGN KEY (id_producer) REFERENCES public.producer(id_producer) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: review review_id_product_8e927e77_fk_product_id_product; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_id_product_8e927e77_fk_product_id_product FOREIGN KEY (id_product) REFERENCES public.product(id_product) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: review review_id_retailer_077f83b2_fk_retailer_id_retailer; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_id_retailer_077f83b2_fk_retailer_id_retailer FOREIGN KEY (id_retailer) REFERENCES public.retailer(id_retailer) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: wishlist wishlist_id_retailer_f880e4c0_fk_retailer_id_retailer; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wishlist
    ADD CONSTRAINT wishlist_id_retailer_f880e4c0_fk_retailer_id_retailer FOREIGN KEY (id_retailer) REFERENCES public.retailer(id_retailer) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: wishlist_item wishlist_item_id_wishlist_0b7b09ed_fk_wishlist_id_wishlist; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wishlist_item
    ADD CONSTRAINT wishlist_item_id_wishlist_0b7b09ed_fk_wishlist_id_wishlist FOREIGN KEY (id_wishlist) REFERENCES public.wishlist(id_wishlist) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

