# Generated by Django 6.0.3 on 2026-05-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(db_column='id_image', primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'image',
            },
        ),
    ]
