# Generated by Django 6.0.3 on 2026-05-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='blob',
            field=models.BinaryField(db_column='blob', default=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='mime_type',
            field=models.CharField(db_column='mime_type', default='application/octet-stream', max_length=100),
            preserve_default=False,
        ),
    ]
