# Generated by Django 6.0.3 on 2026-04-15 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('varejista', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='varejista',
            old_name='user',
            new_name='id_usuario',
        ),
    ]
