# Generated by Django 6.0.3 on 2026-04-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('varejista', '0002_rename_user_varejista_id_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='varejista',
            old_name='id_usuario',
            new_name='user',
        ),
    ]
