# Generated by Django 6.0.3 on 2026-05-10 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0002_remove_image_url_image_blob_image_mime_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultProductImage',
            fields=[
                ('id', models.BigAutoField(db_column='id_default_product_image', primary_key=True, serialize=False)),
                ('product_external_key', models.TextField(db_column='product_external_key', unique=True)),
                ('product_name', models.CharField(blank=True, db_column='product_name', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('image', models.ForeignKey(blank=True, db_column='id_image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_product_images', to='image.image')),
            ],
            options={
                'db_table': 'default_product_image',
                'indexes': [models.Index(fields=['product_external_key'], name='default_pro_product_899833_idx')],
            },
        ),
    ]
