# Generated by Codex on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0002_alter_address_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=6,
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=6,
                max_digits=9,
                null=True,
            ),
        ),
    ]
