# Generated by Django 6.0.3 on 2026-04-15 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='ativa',
            new_name='ativo',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='descricao',
        ),
    ]
