# Generated by Django 6.0.3 on 2026-05-02 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('user', models.OneToOneField(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='retailer', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('document_type', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], max_length=4)),
                ('document_number', models.CharField(max_length=20, unique=True)),
                ('trade_name', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'retailer',
            },
        ),
    ]
