# Generated by Django 6.0.3 on 2026-05-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_fee_value_order_subtotal_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('pix', 'PIX'), ('invoice', 'Boleto Bancário'), ('credit_card', 'Cartão de Crédito')], default=None, max_length=20, null=True),
        ),
    ]
