# Generated by Django 6.0.3 on 2026-05-07 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(db_column='id_wishlist_item', primary_key=True, serialize=False)),
                ('product_external_key', models.TextField(blank=True, null=True)),
                ('product_name', models.CharField(max_length=150)),
                ('wishlist', models.ForeignKey(db_column='id_wishlist', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wishlist.wishlist')),
            ],
            options={
                'db_table': 'wishlist_item',
            },
        ),
    ]
