# Generated by Django 6.0.3 on 2026-05-06 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(db_column='id_producer', primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], max_length=4)),
                ('document_number', models.CharField(max_length=20, unique=True)),
                ('trade_name', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.OneToOneField(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='producer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'producer',
            },
        ),
    ]
