# Generated by Django 6.0.3 on 2026-04-15 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_rename_ativa_categoria_ativo_and_more'),
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='produtor',
            new_name='id_produtor',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='estoque',
        ),
        migrations.AddField(
            model_name='produto',
            name='id_categoria',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='categoria.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade_reservada',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade_total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.FloatField(),
        ),
    ]
