# Generated by Django 6.0.3 on 2026-04-23 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_rename_ativa_categoria_ativo_and_more'),
        ('produto', '0003_alter_produto_preco'),
        ('produtor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='id_produto',
            field=models.AutoField(db_column='id_produto', primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='id_produto',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='id_categoria',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='id_produtor',
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(db_column='id_categoria', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='categoria.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='produtor',
            field=models.ForeignKey(db_column='id_produtor', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='produtor.produtor'),
            preserve_default=False,
        ),
    ]
