# Generated by Django 6.0.3 on 2026-05-06 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retailer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(db_column='id_wishlist', primary_key=True, serialize=False)),
                ('retailer', models.OneToOneField(db_column='id_retailer', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='retailer.retailer')),
            ],
            options={
                'db_table': 'wishlist',
            },
        ),
    ]
