# Generated by Django 6.0.3 on 2026-05-02 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('producer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(db_column='id_product', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_quantity', models.FloatField()),
                ('reserved_quantity', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('category', models.ForeignKey(db_column='id_category', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.category')),
                ('producer', models.ForeignKey(db_column='id_producer', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='producer.producer')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
