# Generated by Codex on 2026-05-20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0003_address_latitude_longitude"),
        ("product", "0002_product_indexes"),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS postgis",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS product_search_vector_idx
                ON product
                USING GIN (
                    to_tsvector(
                        'portuguese',
                        coalesce(name, '') || ' ' || coalesce(description, '')
                    )
                )
            """,
            reverse_sql="DROP INDEX IF EXISTS product_search_vector_idx",
        ),
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS address_postgis_point_idx
                ON address
                USING GIST (
                    (
                        ST_SetSRID(
                            ST_MakePoint(
                                longitude::double precision,
                                latitude::double precision
                            ),
                            4326
                        )::geography
                    )
                )
                WHERE latitude IS NOT NULL AND longitude IS NOT NULL
            """,
            reverse_sql="DROP INDEX IF EXISTS address_postgis_point_idx",
        ),
    ]
