# Generated by Django 6.0.3 on 2026-05-21 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_postgis_search_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='product_is_acti_dbd057_idx',
            old_name='product_active_price_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='product_is_acti_184a97_idx',
            old_name='product_active_created_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='product_name_c4c985_idx',
            old_name='product_name_idx',
        ),
    ]
