# Generated by Django 6.0.3 on 2026-05-10 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0002_remove_image_url_image_blob_image_mime_type'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(db_column='id_product_image', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('image', models.ForeignKey(db_column='id_image', on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='image.image')),
                ('product', models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
            options={
                'db_table': 'product_image',
            },
        ),
    ]
