# Generated by Django 6.0.3 on 2026-05-02 18:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('producer', '0001_initial'),
        ('product', '0001_initial'),
        ('retailer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(db_column='id_review', primary_key=True, serialize=False)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('order', models.ForeignKey(db_column='id_order', on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('producer', models.ForeignKey(db_column='id_producer', on_delete=django.db.models.deletion.CASCADE, to='producer.producer')),
                ('product', models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('retailer', models.ForeignKey(db_column='id_retailer', on_delete=django.db.models.deletion.CASCADE, to='retailer.retailer')),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
