# Generated by Django 6.0.3 on 2026-04-23 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_pedido', '0002_initial'),
        ('pedido', '0002_alter_pedido_id_pedido_rename_id_pedido_pedido_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='id_item',
            field=models.AutoField(db_column='id_item', primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='id_item',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='id_pedido',
        ),
        migrations.AddField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedido.pedido'),
            preserve_default=False,
        ),
    ]
